### ISSUE TITLE
How do I escape reserved characters?

### ISSUE THREAD

**Issue by eight04** [poppinss/haye#1]
> Limitations The keys/values inside the expression cannot have any of the reserved keywords, otherwise parser will mis-behave.

Does it mean that we can't use`,`, `|` in the value? How about some kinds of the following syntax:

* With quotes
	```
	pipe:"value, includes, keyword"
	```
* Escape
	```
	pipe:value\, includes\, keyword
	```

Which would be parsed into:
```js
[
	{ name: "pipe", args: ["value, includes, keyword"] }
]
```

**Comment by thetutlage** [comment]
There is no way escape special chars. One technique I used with Indicative (uses this package) is to introduce a method to define the schema using a function. 

Read more about same here https://indicative.adonisjs.com/docs/syntax-guide#_limitations
